export { default as MenuTile } from './menu-tile.vue'
export { default as MenuProductTile } from './menu-product-tile/menu-product-tile.vue'
export { default as MenuPromoTile } from './menu-promo-tile/menu-promo-tile.vue'
export { default as MenuSurpriseMeTile } from './menu-surprise-me-tile/menu-surprise-me-tile.vue'
export { default as MenuCategoryDefaultTile } from './menu-category-tile/menu-category-default-tile/menu-category-default-tile.vue'
export { default as MenuCategoryCarouselTile } from './menu-category-tile/menu-category-carousel-tile/menu-category-carousel-tile.vue'
export { default as MenuCategoryRecommendationTile } from './menu-category-tile/menu-category-recommendation-tile/menu-category-recommendation-tile.vue'
export { default as CategoryListItem } from './menu-category-tile/category-list-item/category-list-item.vue'
